name: Pipeline_2048
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: self-hosted
    needs: [package]
    steps:      
      - name: Deploy project
        run: cp ./target/game2048.war /usr/local/tomcat/webapps
