name: Pipeline_2048
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      -name: Setup Java
      uses: .m2/repository
      with:
        distribution: 'adopt'
        java-version: 11
      run: mvn compile
