name: Pipeline_2048
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Compile project
        run: mvn compile
