name: Pipeline_2048
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Compile project
        run: mvn compile
        
  test:
    runs-on: [self-hosted, linux]
    needs: [build]
    steps:      
      - name: Test project
        run: mvn test
        
  package:
    runs-on: [self-hosted, linux]
    needs: [build, test]
    steps:      
      - name: Create project
        run: mvn package
        
  deploy:
    runs-on: [self-hosted, linux]
    needs: [package]
    steps:  
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-app-url.com
          environment: production
    
      - name: Deploy project
        run: mvn tomcat7:run
